name: Deploy Compose Web Demo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build
        run: |
          ./compose/gradlew -b ./compose/build.gradle.kts :demo:wasmJsBrowserDistribution --no-configuration-cache

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./compose/demo/build/dist/wasmJs/productionExecutable
